version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: lojinha-db
    restart: always
    environment:
      MYSQL_DATABASE: lojinhadb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lojinha-network

  app:
    build: .
    container_name: lojinha-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    # Injeção das variáveis que o nosso application.properties vai ler
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=lojinhadb
      - DB_USER=root
      - DB_PASSWORD=root
#      - JWT_SECRET=QualquerTextoAbsurdamenteGiganteEAlfanumericoAquiDentro
    networks:
      - lojinha-network

volumes:
  db_data:

networks:
  lojinha-network:
    driver: bridge