services:
  db:
    image: mysql:9.0
    container_name: lojinha-db
    restart: always
    environment:
      # Valores puxados do seu .env
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      # Atualizado para usar a senha do root definida no seu .env
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_ROOT_PASSWORD}",
        ]
      timeout: 5s
      retries: 10

  app:
    build: ./backend
    container_name: lojinha-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Conecta usando as credenciais do usuário 'demon_user' do .env
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

  frontend:
    build: ./frontend
    container_name: lojinha-front
    ports:
      - "80:80"
    depends_on:
      - app
